### ISSUE TITLE
EICrecon with LSan reports memory leaks in JStreamLog and JStreamLogBuffer

### ISSUE THREAD

**Issue by wdconinc** [JeffersonLab/JANA2#372]
Ref. https://github.com/eic/EICrecon/pull/1628

```
=================================================================
==609==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 272 byte(s) in 2 object(s) allocated from:
    #0 0x55e2fb0ba20d in operator new(unsigned long) (/home/runner/work/EICrecon/EICrecon/install/bin/eicrecon+0x10e20d) (BuildId: a5040da1707e76901d07b3ade4bdca35b7daccf2)
    #1 0x7f2d2a6a06d1 in JStreamLog::JStreamLog(std::ostream const&, char const*) (/opt/local/lib/libJANA.so+0x15d6d1) (BuildId: 7ee8b20a986d2d231d4fb255c9a0cd83b13e422c)

Indirect leak of 21 byte(s) in 2 object(s) allocated from:
    #0 0x55e2fb0ba31d in operator new[](unsigned long) (/home/runner/work/EICrecon/EICrecon/install/bin/eicrecon+0x10e31d) (BuildId: a5040da1707e76901d07b3ade4bdca35b7daccf2)
    #1 0x7f2d2a6a13dd in JStreamLogBuffer::JStreamLogBuffer(std::basic_streambuf<char, std::char_traits<char>>*, char const*) (/opt/local/lib/libJANA.so+0x15e3dd) (BuildId: 7ee8b20a986d2d231d4fb255c9a0cd83b13e422c)
```
This started to happen around https://eicweb.phy.anl.gov/containers/eic_container/-/commit/66c92d16d00475a373967f6727b71127472fd083, i.e. the jana2 v2.3.1 to v2.3.2 upgrade.

This could be caused by the `new`s in the following two places:
- https://github.com/JeffersonLab/JANA2/blob/38c0e9ada88918bd51e6d749247fcb2e97d11253/src/libraries/JANA/Compatibility/JStreamLog.cc#L14
- https://github.com/JeffersonLab/JANA2/blob/38c0e9ada88918bd51e6d749247fcb2e97d11253/src/libraries/JANA/Compatibility/JStreamLogBuffer.cc#L22

@nathanwbrei Tagging you here as well.

**Comment by wdconinc** [comment]
> I'm curious if there are other LSAN complaints related to JANA2.

https://github.com/eic/EICrecon/actions/runs/20742462217/job/59552201081#step:7:1630
```
-----------------------------------------------------
Suppressions used:
  count      bytes template
    219      78840 dd4hep::DetElement::DetElement
   1519     298116 dd4hep::DetElementObject::clone
      1        104 dd4hep::VisAttr::VisAttr
   4600     110400 edm4hep::*::create*Buffers
  25660    2633676 libCore.so
      5       8064 libJANA.so
-----------------------------------------------------
```
